Repository LittleSkinCommspt/commspt-bot-manual, pull requests merged in 2023-01, with the labels that each got.

#55 Bump vuepress to beta.60
  package.json
Labels: dependencies

#56 Removed "Restent Ou" Forever
  maintainer.md
Labels: documentation, help wanted

#58 Create develop.md
  .vuepress/config.ts
  develop.md
Labels: documentation

#60 Update &view.* in command.md
  README.md
  commands.md
Labels: documentation, enhancement
